name: Build and Deploy
on:
  push:
    branches:
      - dep-rewrite
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Node
        uses: actions/setup-node@v2
        with:
          node-version: '23.10.0'

      - name: Install
        run: |
          npm ci

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages